# Generated by Django 5.1.6 on 2025-02-28 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_submission_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.challenge'),
        ),
    ]
